### ISSUE TITLE
New Rustic Roads: 125, 126

### ISSUE THREAD

**Issue by mattmahn** [Wiscmapper/WisconsinRusticRoads#1]
The 2024 edition has new Rustic Roads!  But they're missing from this dataset
- [R-125](https://wisconsindot.gov/Pages/travel/road/rustic-roads/rr125.aspx)
- [R-126](https://wisconsindot.gov/Pages/travel/road/rustic-roads/rr126.aspx)

**Comment by Wiscmapper** [comment]
Thanks! I'll work on adding them.
